### ISSUE TITLE
Can't build on `glyphs3` branch

### ISSUE THREAD

**Issue by jlbosse** [firamath/firamath#58]
I am trying to build the fonts myself on the `glyphs3` branch (since it is most up to date), but both python2 and python3 fail. On python2 I get
```bash
$ python2 scripts/build.py --fonts
  File "scripts/build.py", line 24
    def read_glyphs_package(path: str) -> GSFont:
                                ^
SyntaxError: invalid syntax
```
which looks like python2 doesn't like the type hints. If I try python 3 I get the following errors:

```bash
$ python2 scripts/build.py --fonts

Python 3.9.2
fonttools 4.21.1
glyphsLib 5.3.2

Parsing input file 'src/FiraMath.glyphspackage'...
Elapsed: 1.64s

Traceback (most recent call last):
  File "/home/janlukas/System/firamath/scripts/build.py", line 326, in <module>
    build('src/FiraMath.glyphspackage', toml_path='src/FiraMath.toml', output_dir='build/')
  File "/home/janlukas/System/firamath/scripts/build.py", line 315, in build
    font = read_glyphs_package(input_path)
  File "/home/janlukas/System/firamath/scripts/build.py", line 31, in read_glyphs_package
    return Parser(current_type=GSFont).parse(
  File "/usr/lib/python3.9/site-packages/glyphsLib/parser.py", line 51, in parse
    result, i = self._parse(text, 0)
  File "/usr/lib/python3.9/site-packages/glyphsLib/parser.py", line 97, in _parse
    return self._parse_dict(text, i)
  File "/usr/lib/python3.9/site-packages/glyphsLib/parser.py", line 150, in _parse_dict
    i = self._parse_dict_into_object(res, text, i)
  File "/usr/lib/python3.9/site-packages/glyphsLib/parser.py", line 166, in _parse_dict_into_object
    result = self._parse(text, i)
  File "/usr/lib/python3.9/site-packages/glyphsLib/parser.py", line 103, in _parse
    return self._parse_list(text, i)
  File "/usr/lib/python3.9/site-packages/glyphsLib/parser.py", line 193, in _parse_list
    list_item, i = self._parse(text, i)
  File "/usr/lib/python3.9/site-packages/glyphsLib/parser.py", line 97, in _parse
    return self._parse_dict(text, i)
  File "/usr/lib/python3.9/site-packages/glyphsLib/parser.py", line 150, in _parse_dict
    i = self._parse_dict_into_object(res, text, i)
  File "/usr/lib/python3.9/site-packages/glyphsLib/parser.py", line 166, in _parse_dict_into_object
    result = self._parse(text, i)
  File "/usr/lib/python3.9/site-packages/glyphsLib/parser.py", line 103, in _parse
    return self._parse_list(text, i)
  File "/usr/lib/python3.9/site-packages/glyphsLib/parser.py", line 193, in _parse_list
    list_item, i = self._parse(text, i)
  File "/usr/lib/python3.9/site-packages/glyphsLib/parser.py", line 97, in _parse
    return self._parse_dict(text, i)
  File "/usr/lib/python3.9/site-packages/glyphsLib/parser.py", line 150, in _parse_dict
    i = self._parse_dict_into_object(res, text, i)
  File "/usr/lib/python3.9/site-packages/glyphsLib/parser.py", line 169, in _parse_dict_into_object
    res[name], i = result
  File "/usr/lib/python3.9/site-packages/glyphsLib/classes.py", line 3107, in __setitem__
    super().__setitem__(key, value)
  File "/usr/lib/python3.9/site-packages/glyphsLib/classes.py", line 366, in __setitem__
    setattr(self, key, value)
  File "/usr/lib/python3.9/site-packages/glyphsLib/classes.py", line 3213, in <lambda>
    lambda self, value: LayerGuideLinesProxy(self).setter(value),
  File "/usr/lib/python3.9/site-packages/glyphsLib/classes.py", line 986, in setter
    value._parent = self._owner
AttributeError: 'str' object has no attribute '_parent'
```
Building the project with python 3 works on trhe `master` branch after creating the `firamath/releas/fonts` folder.

**Comment by stone-zeng** [comment]
First, it requires python3 (3.9+ I think). Then it uses the dev version of `glyphsLib`, or more precisely, googlefonts/glyphsLib#652 (the current version is 5.2.1.dev156+g927dba2, see [actions](https://github.com/firamath/firamath/runs/2133710640)). So it's better to use a virtual environment and then `pip install` with the `requirements.txt`.
